export const TARGET_WORDS = {
    "3": [
        { word: "CAT", definition: "A small domesticated carnivorous mammal with soft fur." },
        { word: "DOG", definition: "A domesticated carnivorous mammal that typically has a long snout and an acute sense of smell." }
    ],
    "4": [
        { word: "BETA", definition: "A stage of software testing in which a product is released to a limited number of users." },
        { word: "DATA", definition: "Facts and statistics collected together for reference or analysis." },
        { word: "NODE", definition: "A basic unit of a data structure, such as a linked list or tree data structure." },
        { word: "ARCH", definition: "A curved symmetrical structure spanning an opening and typically supporting the weight of a bridge, roof, or wall." },
{ word: "AREA", definition: "A region or part of a town, a country, or the world, or the extent of a two-dimensional surface within a boundary." },
{ word: "ARMY", definition: "An organized military force equipped for fighting on land." },
{ word: "ATOM", definition: "The basic unit of a chemical element, consisting of a nucleus surrounded by electrons." },
{ word: "BABY", definition: "A very young child or animal." },
{ word: "BACK", definition: "The rear surface of the human body from the shoulders to the hips, or the corresponding upper surface of an animal." },
{ word: "BALL", definition: "A solid or hollow spherical or egg-shaped object that is kicked, thrown, or hit in a game." },
{ word: "BAND", definition: "A group of people who have a common interest or purpose, or a company of musicians who play together." },
{ word: "BANK", definition: "A financial establishment that invests money deposited by customers, pays it out when required, and makes loans." },
{ word: "BARK", definition: "The tough protective outer sheath of the trunk and branches of a tree." },
{ word: "BARN", definition: "A large farm building used for storing grain, hay, or straw or for housing livestock." },
{ word: "BASE", definition: "The lowest part or edge of something, especially the part on which it rests or is supported." },
{ word: "BATH", definition: "An act of washing or cleansing the body, or a large container filled with water for this purpose." },
{ word: "BEAD", definition: "A small piece of glass, stone, or similar material, typically rounded and perforated for stringing." },
{ word: "BEAK", definition: "A bird's horny projecting jaws." },
{ word: "BEAM", definition: "A long, sturdy piece of squared timber or metal spanning an opening or part of a building, or a ray of light." },
{ word: "BEAN", definition: "An edible seed, typically kidney-shaped, growing in long pods on certain leguminous plants." },
{ word: "BEAR", definition: "A large, heavy mammal that walks on the soles of its feet, having thick fur and a very short tail." },
{ word: "BELL", definition: "A hollow object, typically made of metal and in the shape of a deep inverted cup, that emits a musical tone when struck." },
{ word: "BELT", definition: "A strip of leather or other material worn around the waist to support clothes or for ornament." },
{ word: "BIKE", definition: "A bicycle or motorcycle." },
{ word: "BIRD", definition: "A warm-blooded egg-laying vertebrate distinguished by the possession of feathers, wings, and a beak." },
{ word: "BITE", definition: "An act of cutting or gripping with the teeth." },
{ word: "BLAD", definition: "The flat cutting edge of a knife, saw, or other tool or weapon." },
{ word: "BOAT", definition: "A small vessel for traveling over water." },
{ word: "BODY", definition: "The physical structure of a person or an animal, including the bones, flesh, and organs." },
{ word: "BOLT", definition: "A metal pin or bar used that screws into a nut to secure things together." },
{ word: "BONE", definition: "Any of the pieces of hard, whitish tissue making up the skeleton in most vertebrates." },
{ word: "BOOK", definition: "A written or printed work consisting of pages bound together in a cover." },
{ word: "BOOT", definition: "A sturdy item of footwear covering the foot and the ankle, and sometimes the lower leg." },
{ word: "BOSS", definition: "A person who is in charge of a worker or organization." },
{ word: "BOWL", definition: "A round, deep dish or basin used for food or liquid." },
{ word: "BULB", definition: "A rounded underground storage organ present in some plants, or a glass component that emits light." },
{ word: "BULL", definition: "An uncastrated male bovine animal." },
{ word: "BUSH", definition: "A shrub or small cluster of shrubs." },
{ word: "CAFE", definition: "A small restaurant selling light meals and drinks." },
{ word: "CAGE", definition: "A structure of bars or wires in which birds or animals are confined." },
{ word: "CAKE", definition: "An item of soft sweet food made from a mixture of flour, fat, eggs, and sugar, baked in an oven." },
{ word: "CALF", definition: "A young bovine animal, especially a domestic cow or bull." },
{ word: "CAMP", definition: "A place with temporary accommodation of huts, tents, or other structures." },
{ word: "CANE", definition: "The hollow jointed stem of a tall grass, or a walking stick." },
{ word: "CAPE", definition: "A sleeveless garment of various lengths, fastened around the neck and hanging loose from the shoulders." },
{ word: "CARD", definition: "A piece of thick, stiff paper or thin pasteboard, used for writing, printing, or games." },
{ word: "CART", definition: "A strong open vehicle with two or four wheels, typically used for carrying loads and pulled by a horse." },
{ word: "CASE", definition: "An instance of a particular situation, or a container for protecting or carrying things." },
{ word: "CASH", definition: "Money in coins or notes, as distinct from checks, money orders, or credit." },
{ word: "CAST", definition: "The actors in a play, film, or television show, or a mold for shaping molten metal or plastic." },
{ word: "CAVE", definition: "A large underground chamber, typically of natural origin, in a hillside or cliff." },
{ word: "CELL", definition: "The smallest structural and functional unit of an organism, or a small room for a prisoner." },
{ word: "CENT", definition: "A monetary unit in various countries, equal to one hundredth of a dollar, euro, or other basic unit." },
{ word: "CHEF", definition: "A professional cook, typically the chief cook in a restaurant or hotel." },
{ word: "CHIN", definition: "The protruding part of the face below the mouth, formed by the apex of the lower jaw." },
{ word: "CHIP", definition: "A small piece of something removed by chopping or breaking, or a thin slice of food." },
{ word: "CITY", definition: "A large town, typically one with a cathedral or a university." },
{ word: "CLAN", definition: "A group of close-knit and interrelated families." },
{ word: "CLAW", definition: "A curved pointed horny nail on each digit of the foot in birds, lizards, and some mammals." },
{ word: "CLAY", definition: "A stiff, sticky fine-grained earth, typically yellow, red, or bluish-gray in color, used for pottery." },
{ word: "CLUB", definition: "An association dedicated to a particular interest or activity, or a heavy stick used as a weapon." },
{ word: "CLUE", definition: "A piece of evidence or information used in the detection of a crime or a puzzle." },
{ word: "COAL", definition: "A combustible black or dark brown rock consisting mainly of carbonized plant matter, used as fuel." },
{ word: "COAT", definition: "An outer garment with sleeves, worn outdoors and typically extending below the hips." },
{ word: "COCK", definition: "A male bird, especially of a domestic fowl." },
{ word: "CODE", definition: "A system of words, letters, figures, or symbols used to represent others of secret or programmatic purposes." },
{ word: "COIL", definition: "A length of something wound in a joined sequence of concentric rings or spirals." },
{ word: "COIN", definition: "A flat, typically round piece of metal with an official stamp, used as money." },
{ word: "COLT", definition: "A young male horse, in particular one less than four years old." },
{ word: "CONE", definition: "A solid or hollow object which tapers from a circular or roughly circular base to a point." },
{ word: "COOK", definition: "A person who prepares and cooks food." },
{ word: "CORD", definition: "Thin, flexible string or rope made from several twisted strands." },
{ word: "CORE", definition: "The tough central part of various fruits, containing the seeds, or the central part of anything." },
{ word: "CORK", definition: "The buoyant, light brown substance obtained from the outer bark of an oak tree, used for bottle stoppers." },
{ word: "CORN", definition: "A cereal plant that yields large grains set in rows on a cob." },
{ word: "COST", definition: "An amount that has to be paid or spent to buy or obtain something." },
{ word: "CREW", definition: "A group of people who work on a ship, aircraft, or train." },
{ word: "CROW", definition: "A large perching bird with mostly glossy black plumage, a heavy bill, and a raucous voice." },
{ word: "CUBE", definition: "A symmetrical three-dimensional shape, either solid or hollow, contained by six equal squares." },
{ word: "CUFF", definition: "The end part of a sleeve, where the material of the sleeve is turned back or a separate band is sewn on." },
{ word: "CURE", definition: "A substance or treatment that cures a disease or condition." },
{ word: "CZAR", definition: "An emperor of Russia before 1917, or a person appointed by government to advise on a policy area." },
{ word: "DAME", definition: "A noblewoman or the title given to a woman holding the female equivalent of a knighthood." },
{ word: "DAMP", definition: "Moisture diffused through the air or a solid substance or body." },
{ word: "DART", definition: "A small pointed missile with feathers or vanes on the back, thrown by hand or shot from a weapon." },
{ word: "DATE", definition: "The day of the month or year as specified by a number, or an oval brown sweet fruit." },
{ word: "DAWN", definition: "The first appearance of light in the sky before sunrise." },
{ word: "DEAN", definition: "The head of a college faculty or department in a university." },
{ word: "DEBT", definition: "Something, typically money, that is owed or due." },
{ word: "DECK", definition: "A structure of planks or plates relative to a ship, or a pack of playing cards." },
{ word: "DEER", definition: "A hoofed grazing or browsing animal, with branched bony antlers that are shed annually." },
{ word: "DESK", definition: "A piece of furniture with a flat or sloped surface for writing or reading." },
{ word: "DIET", definition: "The kinds of food that a person, animal, or community habitually eats." },
{ word: "DISK", definition: "A flat, thin, round object, or a storage device for data." },
{ word: "DOCK", definition: "A structure extending along the shore where ships are loaded and unloaded." },
{ word: "DOLL", definition: "A small model of a human figure, typically one of a baby or girl, used as a child's toy." },
{ word: "DOME", definition: "A rounded vault forming the roof of a building or structure, typically with a circular base." },
{ word: "DOOR", definition: "A hinged, sliding, or revolving barrier that covers an opening to a room, building, or vehicle." },
{ word: "DOVE", definition: "A stocky bird with a small head, short legs, and a cooing voice, often symbolizing peace." },
{ word: "DRUM", definition: "A percussion instrument sounded by being struck with sticks or the hands." },
{ word: "DUCK", definition: "A waterbird with a broad blunt bill, short legs, webbed feet, and a waddling gait." },
{ word: "DUKE", definition: "A nobleman of the highest hereditary rank in various European countries." },
{ word: "DUNE", definition: "A mound or ridge of sand or other loose sediment formed by the wind, especially on the sea coast or in a desert." },
{ word: "DUST", definition: "Fine, dry powder consisting of tiny particles of earth or waste matter lying on the ground or on surfaces." },
{ word: "EARL", definition: "A British nobleman ranking above a viscount and below a marquess." },
{ word: "ECHO", definition: "A sound or series of sounds caused by the reflection of sound waves from a surface back to the listener." },
{ word: "EDGE", definition: "The outside limit of an object, area, or surface." },
{ word: "EYRE", definition: "A circuit court held by itinerant justices in medieval England." },
{ word: "FACE", definition: "The front part of a person's head from the forehead to the chin." },
{ word: "FACT", definition: "A thing that is known or proved to be true." },
{ word: "FAIR", definition: "A gathering of stalls and amusements for public entertainment, or a commercial exhibition." },
{ word: "FANG", definition: "A large, sharp tooth, especially a canine tooth of a venomous snake or predatory animal." },
{ word: "FARM", definition: "An area of land and its buildings, used for growing crops and rearing animals." },
{ word: "FAWN", definition: "A young deer in its first year." },
{ word: "FEAR", definition: "An unpleasant emotion caused by the belief that someone or something is dangerous, likely to cause pain, or a threat." },
{ word: "FEAT", definition: "An achievement that requires great courage, skill, or strength." },
{ word: "FERN", definition: "A flowerless plant that has feathery or deeply fronded leaves and reproduces by spores." },
{ word: "FILE", definition: "A folder or box for holding loose papers, or a tool with a roughened surface for smoothing." },
{ word: "FILM", definition: "A thin flexible strip of plastic coated with light-sensitive material, or a movie." },
{ word: "FIRE", definition: "Combustion or burning, in which substances combine chemically with oxygen from the air and typically give out bright light, heat, and smoke." },
{ word: "FISH", definition: "A limbless cold-blooded vertebrate animal with gills and fins and living wholly in water." },
{ word: "FIST", definition: "A person's hand when the fingers are bent in toward the palm and held there tightly." },
{ word: "FLAG", definition: "A piece of cloth or similar material, typically oblong or square, attachable by one edge to a pole or rope and used as a symbol." },
{ word: "FLAW", definition: "A mark, fault, or other imperfection that mars a substance or object." },
{ word: "FLEA", definition: "A small wingless jumping insect that feeds on the blood of mammals and birds." },
{ word: "FLIP", definition: "A quick, light movement that turns something over or around." },
{ word: "FOAL", definition: "A young horse or related animal, in particular one that is less than one year old." },
{ word: "FOAM", definition: "A mass of small bubbles formed on or in liquid, typically by agitation or fermentation." },
{ word: "FOOD", definition: "Any nutritious substance that people or animals eat or drink or that plants absorb in order to maintain life." },
{ word: "FOOT", definition: "The lower extremity of the leg below the ankle, on which a person stands or walks." },
{ word: "FORD", definition: "A shallow place in a river or stream allowing one to walk or drive across." },
{ word: "FORK", definition: "An implement with two or more prongs used for lifting food to the mouth or holding it when cutting." },
{ word: "FORM", definition: "The visible shape or configuration of something, or a document with blank spaces for inserting information." },
{ word: "FORT", definition: "A fortified building or strategic position." },
{ word: "FOUL", definition: "An unfair play in a game or sport." },
{ word: "FOWL", definition: "A gallinaceous bird kept for its eggs or flesh, such as a domestic cock or hen." },
{ word: "FOXA", definition: "A small carnivorous mammal of the dog family with a pointed muzzle and bushy tail." },
{ word: "FROG", definition: "A tailless amphibian with a short squat body, moist smooth skin, and very long hind legs for leaping." },
{ word: "FUEL", definition: "Material such as coal, gas, or oil that is burned to produce heat or power." },
{ word: "FUND", definition: "A sum of money saved or made available for a particular purpose." },
{ word: "FURY", definition: "Wild or violent anger." },
{ word: "GAME", definition: "A form of play or sport, especially a competitive one played according to rules." },
{ word: "GANG", definition: "An organized group of criminals or a group of young people associated together." },
{ word: "GATE", definition: "A hinged barrier used to close an opening in a wall, fence, or hedge." },
{ word: "GEAR", definition: "Equipment, or a toothed wheel that engages with another to alter the relation between the speed of a driving mechanism." },
{ word: "GERM", definition: "A microorganism, especially one which causes disease." },
{ word: "GIFT", definition: "A thing given willingly to someone without payment." },
{ word: "GIRL", definition: "A female child or adolescent." },
{ word: "GOAL", definition: "The object of a person's ambition or effort, or a pair of posts into which the ball must be sent in sports." },
{ word: "GOAT", definition: "A hardy domesticated ruminant animal that has backward-curving horns and a beard." },
{ word: "GOLD", definition: "A yellow precious metal, valued especially for use in jewelry and decoration." },
{ word: "GOWN", definition: "A long elegant dress worn on formal occasions." },
{ word: "GRID", definition: "A framework of spaced bars that are parallel to or cross each other." },
{ word: "GRIN", definition: "A broad smile." },
{ word: "GRIP", definition: "A firm hold or tight grasp." },
{ word: "GULF", definition: "A deep inlet of the sea almost surrounded by land, with a narrow mouth." },
{ word: "GULL", definition: "A long-winged, web-footed seabird with a white plumage and a grey back and wings." },
{ word: "GURU", definition: "A spiritual teacher, especially one of the Hindu or Buddhist religions, or a trusted expert." },
{ word: "HAIR", definition: "Any of the fine thread-like strands that grow from the skin of humans, mammals, and some other animals." },
{ word: "HALF", definition: "Either of two equal or corresponding parts into which something is or can be divided." },
{ word: "HALL", definition: "An area or passage in a building after entry, or a large building for meetings, concerts, or banquets." },
{ word: "HALO", definition: "A circle of light shown around or above the head of a holy person in a painting or sculpture." },
{ word: "HAND", definition: "The end part of a person's arm beyond the wrist, including the palm, fingers, and thumb." },
{ word: "HARE", definition: "A fast-running long-eared mammal that resembles a large rabbit." },
{ word: "HARP", definition: "A large, triangular stringed instrument plucked with the fingers." },
{ word: "HEAD", definition: "The upper part of the human body, or the front or upper part of the body of an animal, containing the brain, mouth, and sense organs." },
{ word: "HEAP", definition: "An untidy collection of objects placed one on top of another." },
{ word: "HERB", definition: "Any plant with leaves, seeds, or flowers used for flavoring, food, medicine, or perfume." },
{ word: "HERD", definition: "A large group of animals, especially hoofed mammals, that live, feed, or migrate together." },
{ word: "HERO", definition: "A person who is admired or idealized for courage, outstanding achievements, or noble qualities." },
{ word: "HINT", definition: "A slight or indirect indication or suggestion." },
{ word: "HIVE", definition: "A structure in which bees are kept, typically in the form of a box." },
{ word: "HOAX", definition: "A humorous or malicious deception." },
{ word: "HOOF", definition: "The horny part of the foot of an ungulate animal, such as a horse, ox, or deer." },
{ word: "HOOK", definition: "A piece of metal or other material bent or curved at an angle, for catching hold of or hanging things." },
{ word: "HOOP", definition: "A large ring of wood, metal, or plastic." },
{ word: "HORN", definition: "A hard permanent outgrowth, often curved and pointed, found in pairs on the heads of cattle, sheep, goats, and deer." },
{ word: "HOSE", definition: "A flexible tube conveying water or other fluids." },
{ word: "HOST", definition: "A person who receives or entertains other people as guests." },
{ word: "HOUR", definition: "A period of time equal to a twenty-fourth part of a day and night, precisely sixty minutes." },
{ word: "HULL", definition: "The main body of a ship or other vessel, including the bottom, sides, and deck." },
{ word: "HUMP", definition: "A rounded protuberance on the back of a camel or other animal, or a prominent surface elevation." },
{ word: "HUNT", definition: "An act of pursuing and killing a wild animal for sport or food." },
{ word: "HUTT", definition: "A small single-story building of simple or crude construction." },
{ word: "ICON", definition: "A painting of holy figure, or a symbol on a computer screen representing a program." },
{ word: "IDEA", definition: "A thought or suggestion as to a possible course of action." },
{ word: "IDOL", definition: "An image or representation of a god used as an object of worship, or a person adored by fans." },
{ word: "INCH", definition: "A unit of linear measure equal to one twelfth of a foot or 2.54 cm." },
{ word: "IRON", definition: "A strong, magnetic silvery-gray metal, or an appliance used to smooth clothes." },
{ word: "ISLE", definition: "An island or peninsula, especially a small one." },
{ word: "ITEM", definition: "An individual article or unit, especially one that is part of a list, collection, or set." },
{ word: "JACK", definition: "A device for lifting heavy objects, especially vehicles off the ground." },
{ word: "JAIL", definition: "A place for the confinement of people accused or convicted of a crime." },
{ word: "JAWW", definition: "Each of the upper and lower bony structures in vertebrates forming the framework of the mouth and containing the teeth." },
{ word: "JEEP", definition: "A powerful car with four-wheel drive, designed for driving over rough terrain." },
{ word: "JEST", definition: "A thing said or done for amusement, a joke." },
{ word: "JOKE", definition: "A thing that someone says to cause amusement or laughter, especially a story with a punchline." },
{ word: "JOUR", definition: "A diary or daily record of occurrences." },
{ word: "JUDG", definition: "A public officer appointed to decide cases in a law court." },
{ word: "JUIC", definition: "The liquid part that can be extracted from plant or animal tissue, especially fruit." },
{ word: "JUNK", definition: "Old lumber, discarded metal, or other items that can be recycled or are considered worthless." },
{ word: "KALE", definition: "A hardy cabbage of a variety which produces erect stems with large crinkled leaves." },
{ word: "KEEL", definition: "The longitudinal structure along the centerline at the bottom of a vessel's hull." },
{ word: "KING", definition: "The male ruler of an independent state, especially one who inherits the position by right of birth." },
{ word: "KISS", definition: "A touch or caress with the lips as a sign of love, affection, or greeting." },
{ word: "KITE", definition: "A toy consisting of a light frame with thin material stretched over it, flown in the wind at the end of a long string." },
{ word: "KNEE", definition: "The joint between the thigh and the lower leg in humans." },
{ word: "KNIF", definition: "An instrument with a blade fixed into a handle, used for cutting or as a weapon." },
{ word: "KNOT", definition: "A fastening made by tying a piece of string, rope, or something similar." },
{ word: "LACE", definition: "A fine open fabric, typically of cotton or silk, made by looping, twisting, or knitting thread in patterns." },
{ word: "LADS", definition: "A boy or young man." },
{ word: "LAKE", definition: "A large body of water surrounded by land." },
{ word: "LAMB", definition: "A young sheep." },
{ word: "LAMP", definition: "A device for giving light, either one utilizing electricity or a vessel containing oil with a wick." },
{ word: "LANE", definition: "A narrow road, especially in a rural area, or a division of a road or track for a single line of vehicles or runners." },
{ word: "LARK", definition: "A small ground-dwelling songbird, typically with brown streaked plumage." },
{ word: "LASH", definition: "A sharp blow or stroke given with a whip or strap." },
{ word: "LAVA", definition: "Hot molten or semi-fluid rock erupted from a volcano or fissure, or solid rock resulting from cooling of this." },
{ word: "LAWN", definition: "An area of short, mown grass in a yard, garden, or park." },
{ word: "LEAF", definition: "A flattened structure of a higher plant, typically green and bladelike, that is attached to a stem." },
{ word: "LEAK", definition: "An intentional hole or opening through which fluid or gas may escape or enter." },
{ word: "LENS", definition: "A piece of glass or other transparent substance with curved sides for concentrating or dispersing light rays." },
{ word: "LEOP", definition: "A large solitary cat that has a yellowish-brown coat with black spots." },
{ word: "LIAR", definition: "A person who tells lies." },
{ word: "LICE", definition: "A small, wingless, parasitic insect that lives on the skin of mammals and birds." },
{ word: "LIFT", definition: "An apparatus for raising and lowering people or things, or an act of lifting." },
{ word: "LIMB", definition: "An arm or leg of a person or four-legged animal, or a large branch of a tree." },
{ word: "LIME", definition: "A rounded citrus fruit with a thick green skin and fragrant, sour juice." },
{ word: "LINE", definition: "A long, narrow mark or band." },
{ word: "LION", definition: "A large tawny-colored cat that lives in prides, native to Africa and northwestern India." },
{ word: "LIPB", definition: "Either of the two fleshy parts which form the upper and lower edges of the opening of the mouth." },
{ word: "LIST", definition: "A number of connected items or names written or printed consecutively." },
{ word: "LOAD", definition: "A heavy or bulky thing that is being carried or is about to be carried." },
{ word: "LOAF", definition: "A shaped mass of bread baked in one piece." },
{ word: "LOAN", definition: "A thing that is borrowed, especially a sum of money that is expected to be paid back with interest." },
{ word: "LOCK", definition: "A mechanism for keeping a door, lid, or container fastened, typically operated by a key." },
{ word: "LOON", definition: "A large diving waterbird with a sleek black head and a pointed bill." },
{ word: "LOOP", definition: "A shape produced by a curve that bends around and crosses itself." },
{ word: "LORD", definition: "A nobleman or a person who has general authority and power over others." },
{ word: "LUCK", definition: "Success or failure apparently brought by chance rather than through one's own actions." },
{ word: "LUMP", definition: "A compact mass of a substance, especially one without a definite or regular shape." },
{ word: "LUNG", definition: "Each of the pair of organs situated within the rib cage, consisting of elastic sacs with branching passages into which air is drawn." },
{ word: "LYRE", definition: "A stringed instrument like a small harp used by the ancient Greeks." },
{ word: "MAID", definition: "A female domestic servant." },
{ word: "MALT", definition: "Barley or other grain that has been steeped, germinated, and dried, used for brewing or distilling." },
{ word: "MANO", definition: "An estate or large house with land." },
{ word: "MAPS", definition: "A diagrammatic representation of an area of land or sea showing physical features." },
{ word: "MARE", definition: "The female of a horse or other equine animal." },
{ word: "MARK", definition: "A small area on a surface having a different color from its surroundings, or a symbol used in writing." },
{ word: "MASK", definition: "A covering for all or part of the face, worn as a disguise, for protection, or for entertainment." },
{ word: "MAST", definition: "A tall upright post, spar, or structure on a ship or boat, in particular one carrying sails." },
{ word: "MATE", definition: "A fellow member or joint occupant of a specified thing, or a marriage partner." },
{ word: "MEAL", definition: "Any of the regular occasions in a day when food is eaten, or the food eaten on such an occasion." },
{ word: "MESS", definition: "A dirty or untidy state of things or of a place." },
{ word: "MINE", definition: "An excavation in the earth for extracting coal or other minerals." },
{ word: "MINT", definition: "An aromatic plant whose leaves are used for flavoring, or a place where coins are made." },
{ word: "MITE", definition: "A minute arachnid which has four pairs of legs when adult, or a small contribution." },
{ word: "MOAT", definition: "A deep, wide ditch surrounding a castle, fort, or town, typically filled with water and intended as a defense." },
{ word: "MOLE", definition: "A small burrowing insectivorous mammal with dark velvety fur and very small eyes, or a small dark spot on the skin." },
{ word: "MONK", definition: "A member of a religious community of men typically living under vows of poverty, chastity, and obedience." },
{ word: "MOOD", definition: "A temporary state of mind or feeling." },
{ word: "MOON", definition: "The natural satellite of the earth, visible by reflected light from the sun." },
{ word: "MOSS", definition: "A small flowerless green plant that lacks true roots, growing in low carpets or rounded cushions." },
{ word: "MOTH", definition: "An insect with wings that is similar to a butterfly, chiefly nocturnal and having less brightly colored wings." },
{ word: "MULE", definition: "The offspring of a male donkey and a female horse, typically sterile and used as a beast of burden." },
{ word: "MYTH", definition: "A traditional story, especially one concerning the early history of a people or explaining some natural phenomenon." },
{ word: "NAIL", definition: "A small metal spike with a broadened flat head, or the horny covering on the upper surface of the tip of the finger or toe." },
{ word: "NAME", definition: "A word or set of words by which a person, animal, place, or thing is known, addressed, or referred to." },
{ word: "NAPE", definition: "The back of the neck." },
{ word: "NAVE", definition: "The central part of a church building, intended to accommodate most of the congregation." },
{ word: "NECK", definition: "The part of a person's or animal's body connecting the head to the rest of the body." },
{ word: "NEST", definition: "A structure or place made or chosen by a bird for laying eggs and sheltering its young." },
{ word: "NETS", definition: "An openwork fabric of twine or cord used for catching fish or birds." },
{ word: "NEWS", definition: "Information about recent events, newly received notable information." },
{ word: "NOTE", definition: "A brief record of facts or ideas written down as an aid to memory." },
{ word: "NOUN", definition: "A word used to identify any of a class of people, places, or things." },
{ word: "OAKK", definition: "A large tree which bears acorns and has lobed leaves, or its durable wood." },
{ word: "OASI", definition: "A fertile spot in a desert where water is found." },
{ word: "OATH", definition: "A solemn promise, often invoking a divine witness, regarding one's future action or behavior." },
{ word: "OATS", definition: "A cereal plant cultivated chiefly in cool climates, or its grain used for food." },
{ word: "OCEA", definition: "A very large expanse of sea, in particular, each of the main areas of saline water on the earth." },
{ word: "OVEN", definition: "An enclosed compartment, usually part of a cooker, for baking and heating food." },
{ word: "OWLK", definition: "A nocturnal bird of prey with large forward-facing eyes, a facial disc, a hooked beak, and a loud call." },
{ word: "PACK", definition: "A cardboard box or paper container in which goods are issued or sold, or a group of wolves." },
{ word: "PAGE", definition: "One side of a sheet of paper in a collection of sheets bound together." },
{ word: "PAIL", definition: "A cylindrical container with a handle, used for carrying liquids." },
{ word: "PAIN", definition: "Physical suffering or discomfort caused by illness or injury." },
{ word: "PAIR", definition: "A set of two things used together or regarded as a unit." },
{ word: "PALM", definition: "The inner surface of the hand between the wrist and the fingers, or a tropical tree with a crown of long feathers." },
{ word: "PANB", definition: "A metal container used for cooking food." },
{ word: "PARK", definition: "A large public green area in a town, used for recreation." },
{ word: "PART", definition: "An amount or section which, when combined with others, makes up the whole of something." },
{ word: "PATH", definition: "A way or track laid down for walking or made by continual treading." },
{ word: "PEAK", definition: "The pointed top of a mountain, or the highest point of a specified value." },
{ word: "PEAL", definition: "A loud ring or succession of rings of a bell, or a loud outburst of sound." },
{ word: "PEAR", definition: "A yellowish-green edible fruit which is narrow at the stalk and wider at the base." },
{ word: "PEST", definition: "A destructive insect or other animal that attacks crops, food, or livestock." },
{ word: "PIER", definition: "A structure leading out from the shore into the water, used as a landing stage or promenade." },
{ word: "PIGG", definition: "An omnivorous hoofed mammal with a sparse bristly coat and a flat snout." },
{ word: "PILE", definition: "A number of things laid or lying one on top of another." },
{ word: "PILL", definition: "A small round mass of solid medicine to be swallowed whole." },
{ word: "PINE", definition: "An evergreen coniferous tree that has clusters of long needle-shaped leaves." },
{ word: "PINT", definition: "A unit of liquid or dry capacity equal to one eighth of a gallon." },
{ word: "PIPE", definition: "A tube used to convey water, gas, oil, or other fluid substances." },
{ word: "PLAN", definition: "A detailed proposal for doing or achieving something." },
{ word: "PLOT", definition: "A secret plan by a group of people to do something unlawful or harmful, or a small piece of ground." },
{ word: "PLUM", definition: "An oval fleshy fruit which is purple, reddish, or yellow when ripe, containing a flattish stone." },
{ word: "POEM", definition: "A piece of writing that partakes of the nature of both speech and song that is nearly always rhythmical and metaphorical." },
{ word: "POET", definition: "A person who writes poetry." },
{ word: "POLE", definition: "A long, slender, rounded piece of wood or metal, typically placed with one end in the ground as a support." },
{ word: "POND", definition: "A small body of still water formed naturally or by hollowing or embanking." },
{ word: "POOL", definition: "A small area of still water, typically one formed naturally, or an artificial structure for swimming." },
{ word: "PORT", definition: "A town or city with a harbor where ships lade or unlade, or a strong sweet dark red wine." },
{ word: "POST", definition: "A long, sturdy piece of timber or metal set upright in the ground, or an official system for delivering mail." },
{ word: "PRAY", definition: "A solemn request for help or expression of thanks addressed to God or an object of worship." },
{ word: "PREY", definition: "An animal that is caught and killed by another for food." },
{ word: "PRIZ", definition: "A thing given as a reward to the winner of a competition or in recognition of an outstanding achievement." },
{ word: "PUFF", definition: "A short, explosive burst of breath or wind, or a light pastry." },
{ word: "PUMP", definition: "A mechanical device using suction or pressure to raise or move fluids, or inflate tires." },
{ word: "PUPY", definition: "A young dog or related carnivorous mammal." },
{ word: "QUAD", definition: "A large square or rectangular courtyard partly or completely surrounded by buildings." },
{ word: "QUAY", definition: "A stone or metal platform lying alongside or projecting into water for loading and unloading ships." },
{ word: "RACE", definition: "A competition between runners, horses, vehicles, or boats to see which is the fastest." },
{ word: "RAFT", definition: "A flat buoyant structure of timber or other materials fastened together, used as a boat." },
{ word: "RAIL", definition: "A bar or series of bars fixed on upright supports or serving as part of a fence or track." },
{ word: "RAIN", definition: "Moisture condensed from the atmosphere that falls visibly in separate drops." },
{ word: "RAMP", definition: "A sloping surface joining two different levels, as of a floor or road." },
{ word: "RASH", definition: "An area of reddening or tiny spots on a person's skin, typically caused by allergy or infection." },
{ word: "RATE", definition: "A measure, quantity, or frequency, typically one measured against some other quantity or measure." },
{ word: "REED", definition: "A tall, slender plant of the grass family, which grows in water or on marshy ground." },
{ word: "REEF", definition: "A ridge of jagged rock, coral, or sand just above or below the surface of the sea." },
{ word: "RICE", definition: "The swamp-grass which is widely cultivated as a source of food, especially in Asia." },
{ word: "RIDE", definition: "A journey on a horse, bicycle, or motorcycle, or in a vehicle." },
{ word: "RING", definition: "A small circular band, typically of precious metal, worn on a finger." },
{ word: "RIOT", definition: "A violent disturbance of the peace by a crowd." },
{ word: "RISK", definition: "A situation involving exposure to danger." },
{ word: "RIVE", definition: "A large natural stream of water flowing in a channel to the sea, a lake, or another such stream." },
{ word: "ROAD", definition: "A wide way leading from one place to another, especially one with a specially prepared surface which vehicles can use." },
{ word: "ROBE", definition: "A long, loose garment, especially one worn as a formal or ceremonial dress or after a bath." },
{ word: "ROCK", definition: "The solid mineral material forming part of the surface of the earth and other similar planets." },
{ word: "ROOF", definition: "The structure forming the upper covering of a building or a vehicle." },
{ word: "ROOM", definition: "A part or division of a building enclosed by walls, floor, and ceiling." },
{ word: "ROOT", definition: "The part of a plant which attaches it to the ground or to a support, conveying water and nourishment." },
{ word: "ROPE", definition: "A length of thick strong cord made by twisting together strands of hemp, sisal, nylon, or similar material." },
{ word: "ROSE", definition: "A prickly bush or shrub that typically bears fragrant pink, red, yellow, or white flowers." },
{ word: "SACK", definition: "A large bag made of a strong material such as burlap or thick paper, used for storing or carrying goods." },
{ word: "SAIL", definition: "A piece of material extended on a mast to catch the wind and propel a boat or ship." },
{ word: "SALT", definition: "A white crystalline substance which gives seawater its characteristic taste and is used for seasoning food." },
{ word: "SAND", definition: "A loose granular substance resulting from the erosion of siliceous and other rocks and forming beaches and deserts." },
{ word: "SCAR", definition: "A mark left on the skin or within body tissue where a wound, burn, or sore has not completely healed." },
{ word: "SEAM", definition: "A line where two pieces of fabric are sewn together in a garment or other article." },
{ word: "SEAT", definition: "A thing made or used for sitting on, such as a chair or bench." },
{ word: "SEED", definition: "The flowering plant's unit of reproduction, capable of developing into another such plant." },
{ word: "SHAW", definition: "A piece of fabric worn by women over the shoulders or head or wrapped around a baby." },
{ word: "SHED", definition: "A simple roofed structure, typically of wood or metal, used as a storage space or workshop." },
{ word: "SHIP", definition: "A large boat for transporting people or goods by sea." },
{ word: "SHOE", definition: "A covering for the foot, typically made of leather, having a sturdy sole and not extending above the ankle." },
{ word: "SHOP", definition: "A building or part of a building where goods or services are sold to the public." },
{ word: "SHOT", definition: "The firing of a gun or cannon, or a stroke or kick in a sport." },
{ word: "SHOW", definition: "A spectacle or display, typically of an artistic or instructional character." },
{ word: "SIDE", definition: "A position to the left or right of an object, or a flat bounding surface." },
{ word: "SIGN", definition: "A gesture or action used to convey information or an instruction, or a notice displaying info." },
{ word: "SILK", definition: "A fine, strong, soft lustrous fiber produced by silkworms in making cocoons, used to make thread or fabric." },
{ word: "SINK", definition: "A fixed basin with a water supply and a drainpipe." },
{ word: "SKIN", definition: "The thin layer of tissue forming the natural outer covering of the body of a person or animal." },
{ word: "SKIR", definition: "A garment fastened around the waist and hanging down around the legs, typically worn by women." },
{ word: "SLED", definition: "A vehicle on runners for traveling over snow or ice, pulled by draft animals or a vehicle." },
{ word: "SOAP", definition: "A substance used with water for washing and cleaning, made of natural oils or fats." },
{ word: "SOCK", definition: "An item of footwear intended to be worn on the foot and under a shoe, covering the ankle." },
{ word: "SOFA", definition: "A long upholstered seat with a back and arms, for two or more people." },
{ word: "SOIL", definition: "The upper layer of earth in which plants grow, a black or dark brown material typically consisting of organic remains." },
{ word: "SONG", definition: "A short poem or other set of words set to music or meant to be sung." },
{ word: "SOUP", definition: "A liquid food, typically made by boiling meat, fish, or vegetables in stock or water." },
{ word: "SPAW", definition: "The eggs of fish, frogs, or other aquatic creatures, released in a mass into the water." },
{ word: "SPOT", definition: "A small round or roundish mark, differing in color or texture from the surface around it, or a particular location." },
{ word: "SPUR", definition: "A device with a small spike or a spiked wheel that is worn on a rider's heel and used for urging a horse forward." },
{ word: "STAR", definition: "A fixed luminous point in the night sky which is a large, remote incandescent body like the sun." },
{ word: "STEM", definition: "The main long thin part of a plant that rises above the ground and supports the leaves or flowers." },
{ word: "STEW", definition: "A dish of meat and vegetables cooked slowly in liquid in a closed dish or pan." },
{ word: "STOP", definition: "An act of stopping or state of being stopped, or a place where a vehicle stops." },
{ word: "SUIT", definition: "A set of outer clothes made of the same fabric, designed to be worn together, typically consisting of a jacket and trousers." },
{ word: "SWAN", definition: "A large waterbird with a long flexible neck, short legs, webbed feet, and typically all-white plumage." },
{ word: "TANK", definition: "A large receptacle or storage chamber, especially for liquid or gas, or an armored fighting vehicle." },
{ word: "TAPE", definition: "A narrow strip of material, typically plastic, used for binding or fastening." },
{ word: "TASK", definition: "A piece of work to be done or undertaken." },
{ word: "TEAM", definition: "A group of players forming one side in a competitive game or sport, or individuals working together." },
{ word: "TEAR", definition: "A drop of clear salty liquid secreted from the eye when crying or irritated." },
{ word: "TENT", definition: "A portable shelter made of cloth, supported by one or more poles and stretched tight by cords or pegs." },
{ word: "TEXT", definition: "A book or other written or printed work, regarded in terms of its content rather than its physical form." },
{ word: "TIKA", definition: "A mark worn on the forehead by Hindus, or an Indian dish of small pieces of meat." },
{ word: "TILE", definition: "A thin rectangular slab of baked clay or other material, used in overlapping rows for covering roofs, floors, or walls." },
{ word: "TIME", definition: "The indefinite continued progress of existence and events in the past, present, and future regarded as a whole." },
{ word: "TOAD", definition: "A tailless amphibian with a short squat body, dry warty skin, and shorter legs than other similar amphibians." },
{ word: "TOOL", definition: "A device or implement, especially one held in the hand, used to carry out a particular function." },
{ word: "TOUR", definition: "A journey for pleasure in which several places are visited." },
{ word: "TOWN", definition: "An urban area that has a name, defined boundaries, and local government, and that is larger than a village." },
{ word: "TRAM", definition: "A passenger vehicle powered by electricity and conveyed on rails in a city street." },
{ word: "TRAP", definition: "A device or tactic intended to catch an animal or a person unawares." },
{ word: "TRAY", definition: "A flat, shallow container with a raised rim, typically used for carrying food and drink." },
{ word: "TREE", definition: "A woody perennial plant, typically having a single stem or trunk growing to a considerable height." },
{ word: "TRIP", definition: "A journey or excursion, especially for pleasure." },
{ word: "TUBE", definition: "A long, hollow cylinder of metal, plastic, or glass, used for conveying or containing fluids." },
{ word: "TUNA", definition: "A large and active predatory schooling fish of warm seas, extensively fished for food." },
{ word: "TURF", definition: "Grass and the surface layer of earth held together by its roots." },
{ word: "TUSK", definition: "A long, pointed tooth, especially one which protrudes from the mouth of an elephant, walrus, or wild boar." },
{ word: "TWIN", definition: "One of two children or animals born at the same birth." },
{ word: "UNIT", definition: "An individual thing or person regarded as single and complete but also as a component of a larger whole." },
{ word: "VASE", definition: "A decorative container, typically made of glass or china and used as an ornament or for holding cut flowers." },
{ word: "VEIL", definition: "A piece of fine material worn by women to protect or conceal the face." },
{ word: "VEIN", definition: "Any of the tubes forming part of the blood circulation system of the body, carrying in most cases oxygen-depleted blood toward the heart." },
{ word: "VENT", definition: "An opening that allows air, gas, or liquid to pass out of or into a confined space." },
{ word: "VEST", definition: "A sleeveless garment worn on the upper body, typically over a shirt or under a jacket." },
{ word: "VINE", definition: "A climbing or trailing woody-stemmed plant of the grape family." },
{ word: "VISA", definition: "An endorsement on a passport indicating that the holder is allowed to enter, leave, or stay for a specified period of time in a country." },
{ word: "VOIC", definition: "The sound produced in a person's larynx and uttered through the mouth, as speech or song." },
{ word: "WAFE", definition: "A very thin, light, crisp sweet cookie, or a thin disc of unleavened bread used in religious services." },
{ word: "WAGO", definition: "A vehicle used for transporting goods or another specified purpose, typically pulled by horses or a tractor." },
{ word: "WALL", definition: "A continuous vertical brick or stone structure that encloses or divides an area of land." },
{ word: "WAND", definition: "A thin stick or rod, in particular one used by a magician or water diviner." },
{ word: "WASH", definition: "An act of cleansing something, especially the body or clothes, with water." },
{ word: "WASP", definition: "A winged insect with a narrow waist and a stinger, typically having yellow and black stripes." },
{ word: "WAVE", definition: "A long body of water curling into a foam ridge and breaking on the shore, or a rhythmic movement." },
{ word: "WEEK", definition: "A period of seven days." },
{ word: "WELL", definition: "A shaft sunk into the ground to obtain water, oil, or gas." },
{ word: "WEST", definition: "The direction toward the point of the horizon where the sun sets at the equinoxes." },
{ word: "WHAL", definition: "A very large marine mammal with a blowhole on top of the head for breathing." },
{ word: "WHEA", definition: "A cereal plant that is the most important kind grown in temperate countries, the grain of which is ground to make flour." },
{ word: "WHEE", definition: "A circular object that revolves on an axle and is fixed below a vehicle or other object to enable it to move easily." },
{ word: "WHIP", definition: "A strip of leather or cord fastened to a handle, used for flogging or urging on an animal." },
{ word: "WIND", definition: "The perceptible natural movement of the air, especially in the form of a current of air blowing in a particular direction." },
{ word: "WINE", definition: "An alcoholic drink made from fermented grape juice." },
{ word: "WING", definition: "A modified forelimb that bears feathers or thin skin, used by birds, bats, and insects to fly." },
{ word: "WIRE", definition: "Metal drawn out into the form of a thin flexible thread or rod." },
{ word: "WOLF", definition: "A wild carnivorous mammal of the dog family, living and hunting in packs." },
{ word: "WOOD", definition: "The hard fibrous material forming the main substance of the trunk or branches of a tree or shrub." },
{ word: "WOOL", definition: "The fine, soft curly or wavy hair forming the coat of a sheep, goat, or similar animal." },
{ word: "WORD", definition: "A single distinct meaningful element of speech or writing, used with others to form a sentence." },
{ word: "WORK", definition: "Activity involving mental or physical effort done in order to achieve a purpose or result." },
{ word: "WORM", definition: "A limbless creeping insectivore or invertebrate animal with a long, slender soft body." },
{ word: "YARD", definition: "A piece of uncultivated ground adjoining a building, or a unit of linear measure equal to 3 feet." },
{ word: "YARN", definition: "Spun thread used for knitting, weaving, or sewing." },
{ word: "YEAR", definition: "The time taken by the earth to make one revolution around the sun, which is about 365 days." },
{ word: "YOLK", definition: "The yellow internal part of a bird's egg, which provides nourishment for the developing embryo." },
{ word: "ZEAL", definition: "Great energy or enthusiasm in pursuit of a cause or an objective." },
{ word: "ZERO", definition: "The numerical value or figure 0, or the point on a scale from which positive or negative quantities are reckoned." },
{ word: "ZINC", definition: "A silvery-white metal that is a constituent of brass and is used for coating iron and steel to protect against corrosion." },
{ word: "ZONE", definition: "An area or region distinguished from adjacent parts by a distinctive feature or characteristic." },
{ word: "ACID", definition: "A chemical substance that neutralizes alkalis, dissolves some metals, and turns litmus red." },
{ word: "ACRE", definition: "A unit of land area equal to 43,560 square feet." },
{ word: "ALMS", definition: "Money or food given to poor people." },
    { word: "ALTO", definition: "The highest adult male or lowest female singing voice." },
    { word: "AUNT", definition: "The sister of one's father or mother or the wife of one's uncle." },
    { word: "AXLE", definition: "A central shaft for a rotating wheel or gear." },
    { word: "BAIT", definition: "Food placed on a hook or in a net, trap, or fat to entice fish or other animals as prey." },
    { word: "BALE", definition: "A large wrapped or bound bundle of paper, hay, or cotton." },
    { word: "BARD", definition: "A poet, traditionally one reciting epics in a particular oral tradition." },
    { word: "BARO", definition: "A unit of pressure equal to 100 kilopascals." },
    { word: "BASS", definition: "The lowest adult male singing voice, or a type of edible fish." },
    { word: "BAWN", definition: "A defensive wall, or an enclosure surrounding a farmhouse." },
    { word: "BEER", definition: "An alcoholic drink made from yeast-fermented malt flavored with hops." },
    { word: "BEET", definition: "A herbaceous plant widely cultivated as a source of sugar and for its edible root." },
    { word: "BERG", definition: "A large mass of ice detached from a glacier and floating in the sea." },
    { word: "BERTH", definition: "A ship's allotted place at a wharf or dock, or a built-in bed on a ship or train." },
    { word: "BLOC", definition: "A combination of countries, parties, or groups sharing a common purpose." },
    { word: "BLUR", definition: "A thing that cannot be seen or heard clearly." },
    { word: "BOAR", definition: "An uncastrated domestic male pig, or a wild pig." },
    { word: "BOGG", definition: "An area of wet muddy ground that is too soft to support a heavy body." },
    { word: "BOOM", definition: "A loud, deep, resonant sound, or a period of great economic growth." },
    { word: "BOON", definition: "A thing that is helpful or beneficial." },
    { word: "BORE", definition: "A person whose talk or behavior is dull and uninteresting." },
    { word: "BRAD", definition: "A thin, wire nail with a small, asymmetric head." },
    { word: "BRAN", definition: "Pieces of grain husk separated from flour after milling." },
    { word: "BRAT", definition: "A poorly behaved, ill-mannered child." },
    { word: "BRAY", definition: "The loud, harsh cry of a donkey." },
    { word: "BRIM", definition: "The projecting edge around the bottom of a hat, or the top edge of a cup or bowl." },
    { word: "BROW", definition: "A person's forehead, or the ridge over the eye." },
    { word: "BUCK", definition: "The male of certain animals, such as a deer, antelope, or rabbit." },
    { word: "BUMP", definition: "A light blow or a knobby protuberance on a surface." },
    { word: "BUNK", definition: "A narrow shelf-like bed, typically one of two arranged one above the other." },
    { word: "BUNT", definition: "The act of hitting a baseball lightly without swinging the bat." },
    { word: "BUOY", definition: "An anchored float serving as a navigation mark, to show reefs or other hazards." },
    { word: "BURR", definition: "A whirring sound, or a rough edge left on a piece of metal after drilling." },
    { word: "BUST", definition: "A sculpture of a person's head, shoulders, and chest." },
    { word: "CABS", definition: "A taxi, or the driver's compartment in a truck, bus, or train." },
    { word: "CANT", definition: "Hypocritical and sanctimonious talk, or a slope or tilt." },
    { word: "CARD", definition: "A piece of thick, stiff paper or thin pasteboard used for writing or games." },
    { word: "CASK", definition: "A large barrellike container made of wood, metal, or plastic, used for storing liquids, typically alcoholic drinks." },
    { word: "CAUL", definition: "The amniotic membrane enclosing a fetus, which sometimes envelops the head of a child at birth." },
    { word: "CELL", definition: "The smallest structural and functional unit of an organism." },
    { word: "CHAD", definition: "A piece of waste paper produced by punching a hole." },
    { word: "CHAM", definition: "A ruler or potentate, specifically the Khan of Tartary." },
    { word: "CHAR", definition: "A material used for cleaning, or a fish of the salmon family." },
    { word: "CHASM", definition: "A deep fissure in the earth, rock, or another surface." },
    { word: "CHAT", definition: "An informal conversation." },
    { word: "CHUM", definition: "A close friend." },
    { word: "CHUR", definition: "An unpolished or vulgar person." },
    { word: "CION", definition: "A shoot or twig inserted into a slit on the trunk or root of another plant." },
    { word: "CLIP", definition: "A device, typically of bent wire or plastic, for holding things together." },
    { word: "CLOD", definition: "A lump of earth or clay." },
    { word: "CLOG", definition: "A shoe with a thick wooden sole." },
    { word: "CLOT", definition: "A thick, semi-solid mass formed from a liquid, especially blood." },
    { word: "COAX", definition: "An instance of persistent gentle persuasion." },
    { word: "COBS", definition: "The stout central part of an ear of corn on which the grains grow." },
    { word: "COCK", definition: "A male bird, especially of a domestic fowl." },
    { word: "CODA", definition: "The concluding passage of a piece or movement, typically forming an addition to the basic structure." },
    { word: "COID", definition: "A distinct musical chord or harmonic structure." },
    { word: "COLT", definition: "A young male horse, in particular one less than four years old." },
    { word: "COMB", definition: "A strip of plastic or other material with a row of narrow teeth, used for detangling or arranging hair." },
    { word: "COMP", definition: "A free ticket or item provided as a compliment." },
    { word: "COON", definition: "A grayish-brown American mammal with a foxlike face and a ringed tail." },
    { word: "COOP", definition: "A cage or pen for confining poultry." },
    { word: "COOT", definition: "An aquatic bird of the rail family, with blackish plumage and a white bill." },
    { word: "COPE", definition: "A long, loose cloak worn by a priest on ceremonial occasions." },
    { word: "COPS", definition: "A member of a police force." },
    { word: "CORD", definition: "Thin, flexible string or rope made from several twisted strands." },
    { word: "CORE", definition: "The tough central part of various fruits, containing the seeds." },
    { word: "CORM", definition: "A rounded underground storage organ consisting of a swollen stem base, covered with scale leaves." },
    { word: "CORN", definition: "A cereal plant that yields large grains set in rows on a cob." },
    { word: "COSM", definition: "The universe or a complete, self-contained system." },
    { word: "COTS", definition: "A light portable bed, typically one used by campers or the military." },
    { word: "COUP", definition: "A sudden, violent, and illegal seizure of power from a government." },
    { word: "COWL", definition: "A large loose hood, especially one forming part of a monk's habit." },
    { word: "CRAG", definition: "A steep or rugged cliff or rock face." },
    { word: "CRAM", definition: "A tight or crowded mass of people or things." },
    { word: "CRIB", definition: "A young child's bed with barred or latticed sides." },
    { word: "CROP", definition: "A cultivated plant that is grown as food, especially a grain, fruit, or vegetable." },
    { word: "CRUD", definition: "An unpleasantly dirty or sticky substance." },
    { word: "CRUX", definition: "The most decisive or crucial point at issue." },
    { word: "CZAR", definition: "An emperor of Russia before 1917." },
    { word: "DABS", definition: "A small amount of a soft or moist substance." },
    { word: "DADO", definition: "The lower part of the wall of a room, below a molding and above the baseboard." },
    { word: "DAIS", definition: "A low platform for a lectern, seats of honor, or a throne." },
    { word: "DALE", definition: "A valley, especially in northern England." },
    { word: "DAMS", definition: "A barrier constructed to hold back water and raise its level." },
    { word: "DAMP", definition: "Moisture diffused through the air or a solid substance or body." },
    { word: "DEAL", definition: "An agreement entered into by two or more parties for their mutual benefit." },
    { word: "DIAL", definition: "A face of a clock, watch, or sundial that is marked to show the hours." },
    { word: "DICE", definition: "Small cubes with each side having a different number of spots, used in games of chance." },
    { word: "DIRK", definition: "A short dagger of a kind formerly used in the Scottish Highlands." },
    { word: "DIRT", definition: "A substance, such as mud or dust, that soils someone or something." },
    { word: "DIVA", definition: "A celebrated female opera singer." },
    { word: "DOCK", definition: "A structure extending along the shore where ships are loaded and unloaded." },
    { word: "DOER", definition: "A person who acts rather than merely talking or thinking." },
    { word: "DOGS", definition: "A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, and a barking voice." },
    { word: "DOLD", definition: "An ancient, low-lying geological plain." },
    { word: "DOLE", definition: "Benefit paid by the state to the unemployed." },
    { word: "DOLL", definition: "A small model of a human figure, used as a child's toy." },
    { word: "DOLT", definition: "A stupid person." },
    { word: "DOME", definition: "A rounded vault forming the roof of a building or structure." },
    { word: "DOOM", definition: "Death, destruction, or some other terrible fate." },
    { word: "DOPE", definition: "A thick liquid or paste used for specific technical processes, or a drug." },
    { word: "DOTE", definition: "An act of showing excessive fondness or love." },
    { word: "DOWN", definition: "Fine, soft feathers or hairs." },
    { word: "DOXA", definition: "A belief or opinion, especially in philosophical contexts." },
    { word: "DOZE", definition: "A short, light sleep." },
    { word: "DRAB", definition: "A dull, lifeless, or uninteresting color or appearance." },
    { word: "DRAG", definition: "An act of pulling something along a surface with effort." },
    { word: "DRAM", definition: "A small drink of whiskey or other spirits." },
    { word: "DRAY", definition: "A truck or cart without sides, used for hauling heavy loads." },
    { word: "DREG", definition: "The remnants of a liquid left in a container, together with any sediment." },
    { word: "DRIP", definition: "A small drop of a liquid." },
    { word: "DROP", definition: "A small round or pear-shaped portion of liquid that hangs or falls." },
    { word: "DRUB", definition: "A heavy blow or an act of beating." },
    { word: "DRUG", definition: "A medicine or other substance which has a physiological effect when ingested or otherwise introduced into the body." },
    { word: "DUAL", definition: "An element or component that is paired or doubled." },
    { word: "DUEL", definition: "A contest with deadly weapons between two people in order to settle a point of honor." },
    { word: "DUET", definition: "A performance by two singers, musicians, or dancers." },
    { word: "DUNCE", definition: "A person who is slow at learning." },
    { word: "DUNG", definition: "The excrement of animals, especially manure." },
    { word: "DUSK", definition: "The darker stage of twilight in the evening." },
    { word: "DUTY", definition: "A moral or legal obligation, or a responsibility." },
    { word: "DYAD", definition: "Something consists of two elements or parts." },
    { word: "DYKE", definition: "An embankment built to prevent flooding from the sea." },
    { word: "EARN", definition: "A gain or acquisition made through labor." },
    { word: "EASE", definition: "Absence of difficulty or effort." },
    { word: "EAST", definition: "The direction toward the point of the horizon where the sun rises at the equinoxes." },
    { word: "EAVE", definition: "The part of a roof that meets or overhangs the walls of a building." },
    { word: "EDDY", definition: "A circular movement of water, counter to a main current, causing a small whirlpool." },
    { word: "EDICT", definition: "An official order or proclamation issued by a person in authority." },
    { word: "ELAN", definition: "Energy, style, and enthusiasm." },
    { word: "EMIR", definition: "A title of various Muslim rulers." },
    { word: "EMIT", definition: "An act of producing or discharging something." },
    { word: "EMU", definition: "A large flightless fast-running Australian bird resembling the ostrich." },
    { word: "EPIC", definition: "A long poem, typically one derived from ancient oral tradition, narrating the deeds of heroic figures." },
    { word: "EPOCH", definition: "A period of time in history or a person's life, typically one marked by notable events." },
    { word: "ERAS", definition: "A long and distinct period of history with a particular feature or characteristic." },
    { word: "ERGS", definition: "A unit of work or energy, equal to 10 to the power of negative 7 joules." },
    { word: "ESPY", definition: "An act of catching sight of something." },
    { word: "ETCH", definition: "The process or result of using acid to cut a design into a surface." },
    { word: "EXAM", definition: "A formal test of a person's knowledge or proficiency in a subject." },
    { word: "EXIT", definition: "A way out, especially of a public building, room, or vehicle." },
    { word: "EXPO", definition: "A large international exhibition designed to showcase achievements of nations." },
    { word: "FADE", definition: "The process or result of losing color or brightness." },
    { word: "FALL", definition: "An act of dropping down from a higher to a lower position, or the season of autumn." },
    { word: "FAME", definition: "The state of being known or talked about by many people, especially on account of notable achievements." },
    { word: "FATE", definition: "The development of events beyond a person's control, regarded as determined by a supernatural power." },
    { word: "FAUN", definition: "A mythological creature with a man's upper body and a goat's horns and legs." },
    { word: "FAUX", definition: "An imitation or a false thing." },
    { word: "FAWN", definition: "A young deer in its first year." },
    { word: "FEAL", definition: "A faithful or loyal subject." },
    { word: "FEED", definition: "An act of giving food to an animal, or the food itself." },
    { word: "FEND", definition: "An act of warding off or resisting an attack." },
    { word: "FEUD", definition: "A state of prolonged mutual hostility, typically between two families or communities." },
    { word: "FIAT", definition: "A formal authorization or proposition, or an arbitrary decree." },
    { word: "FIEF", definition: "An estate of land, especially one held on condition of feudal service." },
    { word: "FIFE", definition: "A small shrill flute, used chiefly with drums in military bands." },
    { word: "FINE", definition: "A sum of money exacted as a penalty by a court of law or other authority." },
    { word: "FINS", definition: "A flattened appendage on various parts of the body of many aquatic vertebrates, used for propelling." },
    { word: "FIRM", definition: "A business organization, such as a corporation or partnership." },
    { word: "FIVE", definition: "The number equivalent to the sum of two and three." },
    { word: "FLAK", definition: "Anti-aircraft fire, or strong criticism." },
    { word: "FLAN", definition: "A baked tart most commonly filled with custard or fruit." },
    { word: "FLAP", definition: "A piece of something rigid or flexible attached only on one side, that hangs loose or covers an opening." },
    { word: "FLAT", definition: "A suite of rooms usually on one floor of a building, forming a separate residence." },
    { word: "FLAX", definition: "A blue-flowered herbaceous plant that is cultivated for its textile fiber and its nutrient-rich seeds." },
    { word: "FLED", definition: "An act of running away from danger." },
    { word: "FLEE", definition: "An instance of escaping or running away." },
    { word: "FLET", definition: "A piece of wood or lumber used in bowmaking." },
    { word: "FLEW", definition: "An act of aerial movement or travel." },
    { word: "FLEX", definition: "A flexible insulated cable used for connecting an electrical appliance to the mains." },
    { word: "FLIT", definition: "A soft, rapid movement from one place to another." },
    { word: "FLOC", definition: "A loosely clumped mass of fine particles in a liquid." },
    { word: "FLOE", definition: "A sheet of floating ice." },
    { word: "FLOG", definition: "An act of beating someone with a whip or stick as a punishment." },
    { word: "FLOW", definition: "The steady and continuous movement of a fluid or gas." },
    { word: "FLUB", definition: "A botched or bungled attempt." },
    { word: "FLUE", definition: "A duct for smoke and waste gases produced by a fire, a gas heater, or a power station." },
    { word: "FLUX", definition: "The action or process of flowing or flowing out." },
    { word: "FOAL", definition: "A young horse or related animal, in particular one that is less than one year old." },
    { word: "FOID", definition: "A igneous rock containing a high proportion of feldspathoid minerals." },
    { word: "FOIL", definition: "Metal hammered or rolled into a thin flexible sheet, or a fencing sword." },
    { word: "FOLD", definition: "A form or shape produced by the doubling over of a fabric or other pliable material." },
    { word: "FOLK", definition: "People in general, or a specific traditional community." },
    { word: "FONT", definition: "A set of type or characters of one particular face and size, or a basin for holy water." },
    { word: "FOOT", definition: "The lower extremity of the leg below the ankle, on which a person stands or walks." },
    { word: "FOPP", definition: "A man who is concerned with his clothes and appearance in an affected way." },
    { word: "FORA", definition: "A public square or marketplace in an ancient Roman city, used for judicial and public business." },
    { word: "FORD", definition: "A shallow place in a river or stream allowing one to walk or drive across." },
    { word: "FORE", definition: "The front part of something, especially a ship." },
    { word: "FORK", definition: "An implement with two or more prongs used for lifting food to the mouth." },
    { word: "FORM", definition: "The visible shape or configuration of something." },
    { word: "FORT", definition: "A fortified building or strategic position." },
    { word: "FOUR", definition: "The number equivalent to the product of two and two." },
    { word: "FOUT", definition: "An offensive or worthless person." },
    { word: "FRAP", definition: "A binding or wrapping configuration used to secure a structure." },
    { word: "FRAT", definition: "A social organization for male university students." },
    { word: "FRAY", definition: "A situation of intense activity, typically a fight or aggressive competition." },
    { word: "FREE", definition: "A person who is not confined or under constraint." },
    { word: "FRET", definition: "A ridge of wood, metal, or string on the fingerboard of a guitar or similar instrument." },
    { word: "FRIT", definition: "A mixture of silica and fluxes fused at high temperature, used to make glass or ceramic glazes." },
    { word: "FROA", definition: "A traditional tool used for cleaving wood." },
    { word: "FROW", definition: "A woman, especially a Dutch or German one." },
    { word: "FUDG", definition: "A soft rich candy made from sugar, butter, and milk or cream." },
    { word: "FUEL", definition: "Material such as coal, gas, or oil that is burned to produce heat or power." },
    { word: "FUGU", definition: "A pufferfish that is eaten as a Japanese delicacy, which can be poisonous if prepared incorrectly." },
    { word: "FULL", definition: "The maximum amount or capacity of something." },
    { word: "FUME", definition: "An amount of gas or vapor that smells strongly or is dangerous to inhale." },
    { word: "FUND", definition: "A sum of money saved or made available for a particular purpose." },
    { word: "FUNK", definition: "A state of depression, or a music genre with rhythm and blues roots." },
    { word: "FURL", definition: "An act of rolling or folding up a secure structure, such as a sail or flag." },
    { word: "FURY", definition: "Wild or violent anger." },
    { word: "FUSE", definition: "A safety device consisting of a strip of wire that melts and breaks an electric circuit if the current exceeds a safe level." },
    { word: "FUSS", definition: "A display of unnecessary or excessive excitement, activity, or interest." },
    { word: "FUZE", definition: "A mechanical device used to detonate an explosive charge." },
    { word: "FUZZ", definition: "A mass of fine, light fibers or hairs." }
    ],
    "5": [
        { word: "APPLE", definition: "The round fruit of a tree of the rose family, which typically has thin red or green skin." }
    ],
    "6": [
        { word: "WIDGET", definition: "An application, or a component of an interface, that enables a user to perform a function or access a service." }
    ]
};